# Generated by Django 4.2.11 on 2026-05-05 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('investment_type', models.CharField(choices=[('sacco', 'SACCO'), ('mmf', 'MMF (Money Market Fund)'), ('chama', 'Chama'), ('chumz', 'CHUMZ'), ('emergency_fund', 'Emergency Fund'), ('stocks', 'Stocks'), ('treasury_bills', 'Treasury Bills'), ('treasury_bonds', 'Treasury Bonds'), ('crypto', 'Crypto')], db_index=True, max_length=20)),
                ('institution', models.CharField(help_text='Name of institution or account (e.g. CIC MMF, Stanbic SACCO)', max_length=200)),
                ('amount_contributed', models.DecimalField(decimal_places=2, help_text='Amount deposited in Ksh', max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current market or book value in Ksh', max_digits=12)),
                ('goal_target', models.DecimalField(blank=True, decimal_places=2, help_text='Target amount for this investment in Ksh', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Savings Entry',
                'verbose_name_plural': 'Savings Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
