# Generated by Django 4.2.11 on 2026-05-05 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='savingsentry',
            index=models.Index(fields=['user', 'date'], name='savings_sav_user_id_147116_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsentry',
            index=models.Index(fields=['user', 'investment_type'], name='savings_sav_user_id_eb7184_idx'),
        ),
    ]
