# Generated by Django 6.0.5 on 2026-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsentry',
            name='goal_deadline',
            field=models.DateField(blank=True, help_text='Target date to reach the goal', null=True),
        ),
        migrations.AddField(
            model_name='savingsentry',
            name='goal_name',
            field=models.CharField(blank=True, help_text="e.g. 'House Deposit', 'Emergency Fund'", max_length=100),
        ),
    ]
