# Generated by Django 6.0.5 on 2026-05-09 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_savingsentry_goal_deadline_savingsentry_goal_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('investment_type', models.CharField(choices=[('sacco', 'SACCO'), ('mmf', 'MMF (Money Market Fund)'), ('chama', 'Chama'), ('chumz', 'CHUMZ'), ('emergency_fund', 'Emergency Fund'), ('stocks', 'Stocks'), ('treasury_bills', 'Treasury Bills'), ('treasury_bonds', 'Treasury Bonds'), ('crypto', 'Crypto')], db_index=True, max_length=20)),
                ('institution', models.CharField(help_text='Name of institution or account (e.g. CIC MMF, Stanbic SACCO)', max_length=200)),
                ('amount_contributed', models.DecimalField(decimal_places=2, help_text='Amount deposited in Ksh', max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current market or book value in Ksh', max_digits=12)),
                ('goal_target', models.DecimalField(blank=True, decimal_places=2, help_text='Target amount for this investment in Ksh', max_digits=12, null=True)),
                ('goal_name', models.CharField(blank=True, help_text="e.g. 'House Deposit', 'Education Fund'", max_length=100)),
                ('goal_deadline', models.DateField(blank=True, help_text='Target date to reach the goal', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Investment Entry',
                'verbose_name_plural': 'Investment Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('save', 'Save (Move to Vault)'), ('withdraw', 'Withdraw (Take from Vault)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vault Transaction',
                'verbose_name_plural': 'Vault Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='savingsentry',
            name='savings_sav_user_id_147116_idx',
        ),
        migrations.RemoveIndex(
            model_name='savingsentry',
            name='savings_sav_user_id_eb7184_idx',
        ),
        migrations.AddField(
            model_name='investmententry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaulttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='savingsentry',
            name='user',
        ),
        migrations.AddIndex(
            model_name='investmententry',
            index=models.Index(fields=['user', 'date'], name='savings_inv_user_id_3a41b1_idx'),
        ),
        migrations.AddIndex(
            model_name='investmententry',
            index=models.Index(fields=['user', 'investment_type'], name='savings_inv_user_id_d0b7ec_idx'),
        ),
        migrations.DeleteModel(
            name='SavingsEntry',
        ),
    ]
