# Generated by Django 4.2.11 on 2026-05-05 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('housing', 'Housing'), ('personal_care', 'Personal Care'), ('entertainment', 'Entertainment'), ('insurance', 'Insurance'), ('loans_debt', 'Loans & Debt'), ('additional', 'Additional')], db_index=True, help_text='One of 8 fixed categories', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('day_of_week', models.CharField(editable=False, help_text='Auto-calculated from date: Mon, Tue, etc.', max_length=3)),
                ('description', models.CharField(max_length=200)),
                ('subcategory', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent in Ksh', max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense Entry',
                'verbose_name_plural': 'Expense Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
