# Generated by Django 6.0.5 on 2026-05-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('housing', 'Housing'), ('personal_care', 'Personal Care'), ('entertainment', 'Entertainment'), ('insurance', 'Insurance'), ('loans_debt', 'Loans & Debt'), ('additional', 'Additional'), ('miscellaneous', 'Miscellaneous')], db_index=True, help_text='One of 8 fixed categories', max_length=20),
        ),
    ]
