# Generated by Django 6.0.5 on 2026-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expenseentry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='expense_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('one_off', 'One-off'), ('discretionary', 'Discretionary')], default='variable', help_text='Classification for financial logic', max_length=20),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this expense happens every month'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='recurrence_day',
            field=models.IntegerField(blank=True, help_text='Day of month', null=True),
        ),
    ]
