# Generated by Django 6.0.5 on 2026-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='payment_method',
            field=models.CharField(default='bank_transfer', max_length=30),
        ),
    ]
