# Generated by Django 4.2.11 on 2026-05-05 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('housing', 'Housing'), ('personal_care', 'Personal Care'), ('entertainment', 'Entertainment'), ('insurance', 'Insurance'), ('loans_debt', 'Loans & Debt'), ('additional', 'Additional')], db_index=True, help_text='One of 8 fixed categories', max_length=20)),
                ('monthly_budget_ksh', models.DecimalField(decimal_places=2, help_text='Monthly budget limit in Ksh', max_digits=12)),
                ('priority', models.CharField(choices=[('essential', 'Essential'), ('important', 'Important'), ('optional', 'Optional'), ('variable', 'Variable')], default='optional', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Budget',
                'verbose_name_plural': 'Category Budgets',
                'ordering': ['category'],
            },
        ),
    ]
