# Generated by Django 4.2.11 on 2026-05-05 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybudget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='categorybudget',
            index=models.Index(fields=['user', 'category'], name='budgets_cat_user_id_dbec3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together={('user', 'category')},
        ),
    ]
