# Generated by Django 6.0.5 on 2026-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_categorybudget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybudget',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('housing', 'Housing'), ('personal_care', 'Personal Care'), ('entertainment', 'Entertainment'), ('insurance', 'Insurance'), ('loans_debt', 'Loans & Debt'), ('additional', 'Additional'), ('miscellaneous', 'Miscellaneous'), ('savings', 'Savings & Investments')], db_index=True, help_text='One of 8 fixed categories', max_length=20),
        ),
    ]
