# Generated by Django 4.2.11 on 2026-05-05 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('day_of_week', models.CharField(editable=False, help_text='Auto-calculated from date: Mon, Tue, etc.', max_length=3)),
                ('income_source', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance Income'), ('side_hustles', 'Side Hustles'), ('trading', 'Trading Income'), ('business', 'Business Income'), ('dividends', 'Dividends'), ('online_work', 'Online Work')], db_index=True, max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Expected amount in Ksh', max_digits=12, null=True)),
                ('actual_amount', models.DecimalField(decimal_places=2, help_text='Actual amount received in Ksh', max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Income Entry',
                'verbose_name_plural': 'Income Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
