# Generated by Django 4.2.11 on 2026-05-05 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('income', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='incomeentry',
            index=models.Index(fields=['user', 'date'], name='income_inco_user_id_478078_idx'),
        ),
    ]
