# Generated by Django 6.0.5 on 2026-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeentry',
            name='income_layer',
            field=models.CharField(choices=[('committed', 'Committed'), ('expected', 'Expected'), ('actual', 'Actual')], default='actual', help_text='Layer 1: Committed, Layer 2: Expected, Layer 3: Actual', max_length=20),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this income happens every month'),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='recurrence_day',
            field=models.IntegerField(blank=True, help_text='Day of month (e.g. 25 for salary)', null=True),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='variance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-computed: actual - expected', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='variance_percent',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-computed: variance / expected * 100', max_digits=6, null=True),
        ),
    ]
